### ISSUE TITLE
New documentation v3.0

### ISSUE THREAD

**Issue by joseluisq** [joseluisq/gimage#23]
### ToDo
https://joseluisq.github.io/gimage/

- [x] Introduction
- [x] Getting Started
- [x] Classes 
  - [x] Image
  - [x] Figure
  - [x] Text
  - [x] Canvas
- [x] Examples 
  - [x] Cropping
  - [x] Swapping formats
  - [x] Resizing
  - [x] Rotation
  - [x] Creating figures
  - [x] Text embedding
  - [x] Composing with canvas
  - [x] Render images in-memory
  - [x] Creating a presentation card
- [x] API Documentation
